export const BASE_URL = process.env.EXPO_PUBLIC_API_URL;
export const WEBSOCKET_URl = process.env.EXPO_PUBLIC_WEBSOCKET_URL;
export const GOOGLE_MAPS_API_KEY_ANDROID = process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_ANDROID;
export const GOOGLE_MAPS_API_KEY_IOS = process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_IOS;